import assert from 'node:assert/strict';
import * as THREE from '../dist/lib/three.module.js';
import {World} from '../dist/world.js';
import {Game} from '../dist/simulation.js';
import {createSporeBall} from '../dist/spore-ball.js';
import {burstSporePod} from '../dist/spore-effects.js';
import {windView,animateWind} from '../dist/setpieces.js';
import {disposeBranch} from '../dist/streaming.js';
const game=new Game();game.start(1);
const w=Object.assign(Object.create(World.prototype),{currentLevel:game.level,mat:{},platforms:new Map(),levelRoot:new THREE.Group(),fxRoot:new THREE.Group(),particles:[],reducedMotion:false});
const seal=game.level.platforms.find(s=>s.id==='tree-seal'),root=new THREE.Group();root.position.set(seal.x,seal.y,0);w.levelRoot.add(root);createSporeBall(w,seal,root);w.platforms.set(seal.id,{root});
const geometry=[],materials=[];root.traverse(o=>{if(o.geometry)geometry.push(o.geometry);if(o.material)materials.push(o.material);});
let originalDisposed=0;for(const resource of [...new Set([...geometry,...materials])])resource.addEventListener('dispose',()=>originalDisposed++);
burstSporePod(w,{platformId:seal.id,x:seal.x,y:seal.y,w:seal.w});
assert(w.particles.some(p=>p.kind==='spore-shell'));assert(w.particles.some(p=>p.cloud));assert(w.particles.some(p=>p.kind==='spore-bloom'&&!p.cloud));assert(w.particles.length<=36);
const frozen=JSON.stringify(w.particles.map(p=>p.mesh.position.toArray()));w.updateParticles(0);assert.equal(JSON.stringify(w.particles.map(p=>p.mesh.position.toArray())),frozen);
const shell=w.particles.find(p=>p.kind==='spore-shell'),start=shell.mesh.position.clone();
let disposed=0,total=0;for(const p of w.particles){const resources=[...(p.ownedMaterials||[]),...(p.ownedGeometry?[p.mesh.geometry]:[])];total+=resources.length;for(const r of resources)r.addEventListener('dispose',()=>disposed++);}
w.updateParticles(.15);assert(shell.mesh.position.distanceTo(start)>.1);assert(w.particles.some(p=>p.cloud&&p.mesh.scale.x>p.restScale.x));
for(let i=0;i<120;i++)w.updateParticles(1/60);
assert.equal(w.particles.length,0);assert.equal(w.fxRoot.children.length,0);assert.equal(disposed,total);assert.equal(originalDisposed,0,'burst cleanup does not dispose the source sculpture');
w.reducedMotion=true;burstSporePod(w,{platformId:seal.id,x:seal.x,y:seal.y});assert(w.particles.length<=5);assert(!w.particles.some(p=>p.kind==='spore-shell'));for(let i=0;i<120;i++)w.updateParticles(1/60);
const wind=game.level.winds.find(s=>s.channel===seal.releases);wind.active=false;const view=windView(w,wind);animateWind(view,0);assert(!view.root.visible);
wind.active=true;animateWind(view,1);assert(view.root.visible&&view.clouds.length);const positions=view.bits.map(m=>m.position.clone());animateWind(view,1.1);assert(view.bits.some((m,i)=>m.position.y>positions[i].y));
const pose=()=>JSON.stringify([...view.bits,...view.clouds].map(m=>[m.position.toArray(),m.scale.toArray(),m.rotation.toArray()]));
const moving=pose();animateWind(view,1.1);assert.equal(pose(),moving,'simulation time freezes wind on pause');animateWind(view,2,true);const quiet=pose();animateWind(view,7,true);assert.equal(pose(),quiet,'reduced motion keeps the spore field static');
for(const m of view.bits)assert(m.position.x>=0&&m.position.x<=wind.w&&m.position.y>=0&&m.position.y<=wind.h);
wind.active=false;animateWind(view,8);assert(!view.root.visible);
disposeBranch(w,view.root);assert(!view.root.parent);
console.log('PASS spore explosion and wind: shell/billow/pollen layers, pause, bounded burst, owned-resource cleanup, activation, ascent and reduced motion');
