// Emits a lucide subset containing only the icons this game can actually ask
// for. The shipped bundle carries 1,939 icons (388 KB) so that roughly two
// dozen buttons can have a glyph.
//
// Names are collected by over-approximation on purpose: every kebab-case string
// literal anywhere in dist/ is treated as a candidate and kept if lucide has an
// icon by that name. Icon names reach createIcons through lookup tables and
// ternaries as well as direct calls, so anything narrower risks a button that
// renders in dev and comes up blank in the build. A few unused glyphs cost
// about a hundred bytes each.
import {readFileSync,readdirSync,writeFileSync,mkdirSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';

const root=join(dirname(fileURLToPath(import.meta.url)),'..');
const pascal=name=>name.split('-').map(p=>p[0].toUpperCase()+p.slice(1)).join('');

export function collectIconNames(dir=join(root,'dist')){
  const found=new Set();
  const walk=path=>{
    for(const entry of readdirSync(path,{withFileTypes:true})){
      const full=join(path,entry.name);
      if(entry.isDirectory()){if(entry.name!=='assets'&&entry.name!=='lib')walk(full);continue;}
      if(!/\.(js|html)$/.test(entry.name))continue;
      for(const m of readFileSync(full,'utf8').matchAll(/["'`]([a-z][a-z0-9]*(?:-[a-z0-9]+)*)["'`]/g))found.add(m[1]);
    }
  };
  walk(dir);
  return found;
}

export function loadLucideIcons(){
  const source=readFileSync(join(root,'dist/lib/lucide.min.js'),'utf8');
  const sandbox={};sandbox.globalThis=sandbox;sandbox.window=sandbox;sandbox.self=sandbox;
  sandbox.document={createElement:()=>({}),querySelectorAll:()=>[]};
  vm.createContext(sandbox);vm.runInContext(source,sandbox);
  if(!sandbox.lucide?.icons)throw new Error('lucide.min.js did not expose an icons table');
  return sandbox.lucide.icons;
}

export function buildIconModule(){
  const icons=loadLucideIcons(),candidates=collectIconNames();
  const subset={};
  for(const name of [...candidates].sort()){
    const data=icons[pascal(name)];
    if(data)subset[name]=data;
  }
  const module=`// Generated by scripts/build-icons.mjs — do not edit.
// ${Object.keys(subset).length} of ${Object.keys(icons).length} lucide icons.
const I=${JSON.stringify(subset)};
const D={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor","stroke-width":2,"stroke-linecap":"round","stroke-linejoin":"round"};
const node=([tag,attrs,kids=[]])=>{
  const el=document.createElementNS("http://www.w3.org/2000/svg",tag);
  for(const k in attrs)if(attrs[k]!=null)el.setAttribute(k,attrs[k]);
  for(const kid of kids)el.appendChild(node(kid));
  return el;
};
const classesOf=a=>!a||!a.class?[]:Array.isArray(a.class)?a.class:String(a.class).split(" ").filter(Boolean);
function createIcons({icons=I,nameAttr="data-lucide",attrs={},root=document}={}){
  for(const el of Array.from(root.querySelectorAll("["+nameAttr+"]"))){
    const name=el.getAttribute(nameAttr);
    if(name==null)continue;
    const data=icons[name];
    if(!data){console.warn("[icons] no glyph for "+name);continue;}
    const own={};
    for(const a of Array.from(el.attributes))own[a.name]=a.value;
    const aria=own["aria-label"]?{}:{"aria-hidden":"true"};
    const merged={...D,"data-lucide":name,...aria,...attrs,...own};
    const cls=["lucide","lucide-"+name,...classesOf(own),...classesOf(attrs)].filter(Boolean).join(" ");
    if(cls)merged.class=cls;
    el.parentNode&&el.parentNode.replaceChild(node(["svg",merged,data]),el);
  }
}
const lucide={icons:I,createIcons};
globalThis.lucide=lucide;
export {createIcons,I as icons};
export default lucide;
`;
  return {module,names:Object.keys(subset),total:Object.keys(icons).length};
}

if(import.meta.url===`file://${process.argv[1]}`){
  const {module,names,total}=buildIconModule();
  const out=join(root,'dist/lib/lucide-subset.js');
  mkdirSync(dirname(out),{recursive:true});
  writeFileSync(out,module);
  console.log(`lucide subset: ${names.length}/${total} icons, ${(module.length/1024).toFixed(1)} KB`);
  console.log(names.join(' '));
}
