#!/usr/bin/env python3
"""Bake the continuous hand and arrow sculptures; requires NumPy and scikit-image.

Run from any directory: python3 scripts/prepare-shape-hand.py
The generated JavaScript embeds the mesh so the cue needs no asynchronous load.
"""

import base64
from pathlib import Path
import textwrap

import numpy as np
from skimage.measure import marching_cubes


SPACING = 0.036
ORIGIN = np.array([-0.82, -0.82, -0.38])
END = np.array([0.73, 1.13, 0.38])
axes = [np.arange(a, b + SPACING * 0.5, SPACING) for a, b in zip(ORIGIN, END)]
points = np.stack(np.meshgrid(*axes, indexing="ij"), axis=-1)


def ellipsoid(center, radii, angle=0):
    """Approximate signed distance to an ellipsoid rotated in the picture plane."""
    q = points - np.array(center)
    c, s = np.cos(angle), np.sin(angle)
    q = np.stack([c * q[..., 0] + s * q[..., 1],
                  -s * q[..., 0] + c * q[..., 1], q[..., 2]], axis=-1)
    k0 = np.linalg.norm(q / radii, axis=-1)
    k1 = np.linalg.norm(q / np.square(radii), axis=-1)
    return k0 * (k0 - 1) / np.maximum(k1, 1e-8)


def capsule(start, end, radius, depth=1):
    q = points - np.array(start)
    segment = np.array(end) - start
    q[..., 2] /= depth
    segment[2] /= depth
    t = np.clip(np.sum(q * segment, axis=-1) / np.dot(segment, segment), 0, 1)
    return np.linalg.norm(q - t[..., None] * segment, axis=-1) - radius


def join(a, b, softness):
    """Polynomial smooth union joins the fingers without intersecting seams."""
    h = np.maximum(softness - np.abs(a - b), 0) / softness
    return np.minimum(a, b) - h * h * softness * 0.25


# Back of the hand faces +z. Its upper-left index is independent of the drag
# direction: the animation moves the whole hand along the directional arrow.
field = ellipsoid([0.065, -0.085, -0.028], [0.40, 0.425, 0.204], -0.09)
# A short integrated wrist rounds off the lower-right heel of the palm.
field = join(field, ellipsoid([0.21, -0.465, -0.019], [0.205, 0.205, 0.166], -0.29), 0.14)
# The thumb has its own lower-left silhouette and a broad, joined base.
field = join(field, ellipsoid([-0.24, -0.27, 0.025], [0.235, 0.145, 0.147], -0.29), 0.07)
field = join(field, ellipsoid([-0.45, -0.205, 0.035], [0.16, 0.123, 0.139], -0.55), 0.065)
field = join(field, capsule([-0.19, 0.13, -0.005], [-0.535, 0.80, -0.006], 0.14, 0.91), 0.08)
# Three curled fingers form a scalloped knuckle row across the top. Their
# different heights and widths retain the reference's hand-shaped silhouette.
for center, radii, angle in [
    ([-0.055, 0.30, -0.019], [0.146, 0.248, 0.179], 0.06),
    ([0.162, 0.302, -0.028], [0.144, 0.249, 0.180], 0.08),
    ([0.349, 0.23, -0.041], [0.127, 0.239, 0.175], 0.15),
]:
    field = join(field, ellipsoid(center, radii, angle), 0.052)

vertices, faces, normals, _ = marching_cubes(
    field, 0, spacing=(SPACING,) * 3, allow_degenerate=False,
)
vertices += ORIGIN
vertices[:, 2] += 0.04
# Marching cubes reports inward field normals for this negative-inside SDF;
# triangle winding already faces outward. Keep the smooth field normals.
normals *= -1
normals /= np.linalg.norm(normals, axis=1)[:, None]

assert len(vertices) < 65536 and len(faces) <= 10000
assert np.isfinite(vertices).all() and np.isfinite(normals).all()
# Require one watertight surface, rather than overlapping primitive meshes.
edges = np.sort(np.concatenate([faces[:, [0, 1]], faces[:, [1, 2]], faces[:, [2, 0]]]), axis=1)
_, counts = np.unique(edges, axis=0, return_counts=True)
assert np.all(counts == 2), "The hand must be a closed manifold."
neighbors = [set() for _ in vertices]
for a, b in edges:
    neighbors[a].add(b)
    neighbors[b].add(a)
seen, todo = {0}, [0]
while todo:
    for adjacent in neighbors[todo.pop()]:
        if adjacent not in seen:
            seen.add(adjacent)
            todo.append(adjacent)
assert len(seen) == len(vertices), "The fingers must join the palm."
triangles = vertices[faces]
face_normals = np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0])
assert np.all(np.sum(face_normals * normals[faces].mean(axis=1), axis=1) > 0), "Outward winding required."


def embedded(name, data):
    encoded = base64.b64encode(data).decode("ascii")
    return f"const {name}=\n" + "+\n".join(f"  '{line}'" for line in textwrap.wrap(encoded, 120)) + ";\n"


module = """// Generated by scripts/prepare-shape-hand.py; edit that sculpture to regenerate.
// One continuous hand with a rounded index, three knuckles, thumb and wrist.
import * as THREE from './lib/three.module.js';

"""
module += embedded("HAND_POSITIONS", np.rint(vertices * 32767).astype("<i2").tobytes())
module += embedded("HAND_NORMALS", np.rint(normals * 127).astype("i1").tobytes())
module += embedded("HAND_INDICES", faces.astype("<u2").tobytes())
hand_count = (len(vertices), len(faces))

# A rounded shaft and chevron share the same smooth sculpted surface as the
# hand. Baking their union avoids seams or flat faces at the arrow junction.
arrow = capsule([-0.50, 0, 0], [0.32, 0, 0], 0.115)
for y in [-0.34, 0.34]:
    arrow = join(arrow, capsule([-0.10, y, 0], [0.32, 0, 0], 0.13), 0.055)
vertices, faces, normals, _ = marching_cubes(
    arrow, 0, spacing=(SPACING,) * 3, allow_degenerate=False,
)
vertices += ORIGIN
normals *= -1
normals /= np.linalg.norm(normals, axis=1)[:, None]
module += embedded("ARROW_POSITIONS", np.rint(vertices * 32767).astype("<i2").tobytes())
module += embedded("ARROW_NORMALS", np.rint(normals * 127).astype("i1").tobytes())
module += embedded("ARROW_INDICES", faces.astype("<u2").tobytes())
module += """
const decode=data=>Uint8Array.from(atob(data),c=>c.charCodeAt(0));

function geometryFrom(positionsData,normalsData,indicesData,name){
  // Decode into fresh owned buffers; a level can release its cue independently.
  const packed=decode(positionsData),positions=new Float32Array(packed.length/2);
  const bytes=new DataView(packed.buffer);
  for(let i=0;i<positions.length;i++)positions[i]=bytes.getInt16(i*2,true)/32767;
  const indexBytes=decode(indicesData),indexView=new DataView(indexBytes.buffer);
  const indices=new Uint16Array(indexBytes.length/2);
  for(let i=0;i<indices.length;i++)indices[i]=indexView.getUint16(i*2,true);
  const geometry=new THREE.BufferGeometry();
  geometry.name=name;
  geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));
  geometry.setAttribute('normal',new THREE.BufferAttribute(new Int8Array(decode(normalsData).buffer),3,true));
  geometry.setIndex(new THREE.BufferAttribute(indices,1));
  geometry.computeBoundingBox();geometry.computeBoundingSphere();
  return geometry;
}

export const createHandGeometry=()=>geometryFrom(HAND_POSITIONS,HAND_NORMALS,HAND_INDICES,'Continuous clay gesture hand');
export const createArrowGeometry=()=>geometryFrom(ARROW_POSITIONS,ARROW_NORMALS,ARROW_INDICES,'Rounded clay gesture arrow');
"""
destination = Path(__file__).resolve().parents[1] / "dist" / "shape-hand-geometry.js"
destination.write_text(module)
print(f"Wrote {destination}: hand {hand_count}, arrow {len(vertices), len(faces)} vertices/triangles, {len(module):,} bytes.")
